//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Orders
    {
        public int order_id { get; set; }
        public Nullable<int> cart_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public Nullable<int> coupon_id { get; set; }
        public Nullable<int> bill_amount { get; set; }
        public string payment_method { get; set; }
    
        public virtual Tbl_Cart Tbl_Cart { get; set; }
        public virtual Tbl_Coupons Tbl_Coupons { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
