//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Tbl_Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Products()
        {
            this.Tbl_Cart = new HashSet<Tbl_Cart>();
            this.Tbl_Cart_Items = new HashSet<Tbl_Cart_Items>();
        }
    
        public int product_id { get; set; }
        [Required]
        public string product_name { get; set; }
        [Required]
        public Nullable<int> category_id { get; set; }
        [Required]
        public Nullable<int> product_price { get; set; }
        [Required]
        public int product_qty { get; set; }
        [Required]
        [DisplayName("Upload File")]
        public string product_image { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Cart> Tbl_Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Cart_Items> Tbl_Cart_Items { get; set; }
        public virtual Tbl_Categories Tbl_Categories { get; set; }
    }
}
