//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Cart_Items
    {
        public int cart_items_id { get; set; }
        public Nullable<int> cart_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> product_qty { get; set; }
        public string product_name { get; set; }
        public Nullable<decimal> product_price { get; set; }
        public decimal total_val { get; set; }

        public virtual Tbl_Cart Tbl_Cart { get; set; }
        public virtual Tbl_Products Tbl_Products { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
